/**
 * sAgent 完整知识图谱种子数据
 *
 * 覆盖 Node.js + React 全栈氛围编程学习的 7 大模块、69 个知识点
 * 与 lecture-content.data.ts 和 exercise-data.ts 完全对齐
 *
 * 设计理念：
 * 1. 渐进式 — 从基础到高级，严格按前置依赖链路推进
 * 2. 实战导向 — 每个知识点都有明确的编码能力评估标准
 * 3. 个性化 — 不同起点的学生可走不同路径
 * 4. 闭环反馈 — 掌握度追踪 + 自适应推荐
 * 5. 优先级 — P0 核心必学 / P1 常用进阶 / P2 进阶优化 / P3 底层原理
 */

import { KnowledgePoint } from '../../entities/knowledge-point.entity';

/** 快速构建知识点 */
function kp(
  nodeId: string,
  name: string,
  domain: string,
  module: string,
  category: string,
  difficulty: number,
  estimatedMinutes: number,
  description: string,
  prerequisites: string[],
  dependents: string[],
  skills: string[],
  assessmentCriteria: { basic: string; intermediate: string; advanced: string },
  priority: string = 'P1',
  resources: Record<string, string> = {},
): Partial<KnowledgePoint> {
  return {
    nodeId,
    name,
    domain,
    module,
    category,
    difficulty,
    estimatedMinutes,
    description,
    prerequisites,
    dependents,
    skills,
    assessmentCriteria,
    priority,
    resources,
    version: '1.0',
    status: 'published',
  };
}

// ============================================================
// Module 1: JavaScript 核心基础 (javascript-basics)
// 从零开始掌握 JavaScript 语言核心
// ============================================================

const JS_BASICS: Partial<KnowledgePoint>[] = [
  kp('JS-001', '变量与数据类型', 'vibe_coding', 'javascript-basics', '语言基础', 1, 30,
    '理解 JavaScript 的 7 种基本数据类型、引用类型，掌握 let/const/var 声明及区别，理解动态类型与 typeof',
    [], ['JS-002', 'JS-005', 'JS-006'], ['javascript'],
    { basic: '能用 let/const 声明变量，用 typeof 判断类型', intermediate: '理解原始类型与引用类型的区别，能解释类型转换规则', advanced: '能解释 Symbol/BigInt 的使用场景，理解装箱与拆箱' },
    'P0',
    { mdn: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Data_structures' },
  ),
  kp('JS-002', '运算符与表达式', 'vibe_coding', 'javascript-basics', '语言基础', 1, 25,
    '掌握算术、比较、逻辑、位运算符，理解隐式类型转换，掌握运算符优先级和短路求值',
    ['JS-001'], ['JS-003'], ['javascript'],
    { basic: '能使用 +−*/% 及比较运算符', intermediate: '理解 === 与 == 区别，掌握逻辑短路求值', advanced: '理解位运算符和运算符优先级表' },
    'P0',
  ),
  kp('JS-003', '条件与循环', 'vibe_coding', 'javascript-basics', '流程控制', 1, 35,
    '掌握 if/else、switch、for/while/do-while、for...of/for...in，理解 break/continue 及标签语句',
    ['JS-002'], ['JS-004'], ['javascript'],
    { basic: '能编写 if/else 和 for 循环', intermediate: '能使用 for...of/for...in 遍历，理解 break/continue', advanced: '理解标签语句和迭代器协议' },
    'P0',
  ),
  kp('JS-004', '函数基础', 'vibe_coding', 'javascript-basics', '函数', 1, 40,
    '掌握函数声明、表达式、箭头函数、默认参数、剩余参数，理解函数是一等公民',
    ['JS-003'], ['JS-005', 'JS-008'], ['javascript'],
    { basic: '能声明和调用函数，使用参数和返回值', intermediate: '能使用箭头函数和默认参数，理解函数提升', advanced: '理解函数是一等公民，能用函数组合解决复杂问题' },
    'P0',
  ),
  kp('JS-005', '数组方法', 'vibe_coding', 'javascript-basics', '数据结构', 2, 45,
    '掌握数组 CRUD、遍历方法（forEach/map/filter/reduce/find/some/every），理解不可变操作',
    ['JS-001', 'JS-004'], ['JS-010', 'JS-011'], ['javascript', 'functional'],
    { basic: '能用 push/pop/shift，遍历数组', intermediate: '能用 map/filter/reduce 处理数据转换', advanced: '能链式组合数组方法实现复杂数据管道' },
    'P0',
  ),
  kp('JS-006', '字符串与模板字面量', 'vibe_coding', 'javascript-basics', '语言基础', 1, 25,
    '掌握字符串方法（slice/split/includes/replace/trim），理解模板字面量和标签模板',
    ['JS-001'], ['JS-007'], ['javascript'],
    { basic: '能用模板字面量拼接字符串', intermediate: '能用 slice/split/includes 处理字符串', advanced: '理解标签模板和 Unicode 处理' },
    'P0',
  ),
  kp('JS-007', '解构与展开', 'vibe_coding', 'javascript-basics', '语法糖', 2, 30,
    '掌握数组/对象解构赋值、展开运算符、剩余参数，理解浅拷贝与合并',
    ['JS-006'], ['JS-011', 'REACT-003'], ['javascript', 'react'],
    { basic: '能用数组解构和对象解构', intermediate: '能用展开运算符合并数组/对象', advanced: '理解嵌套解构、默认值和解构与迭代器的配合' },
    'P0',
  ),
  kp('JS-008', '闭包与作用域', 'vibe_coding', 'javascript-basics', '核心概念', 2, 50,
    '理解词法作用域、闭包原理、块级作用域，掌握闭包的典型应用和内存陷阱',
    ['JS-004'], ['JS-009', 'REACT-003'], ['javascript'],
    { basic: '理解函数作用域和块级作用域区别', intermediate: '能编写闭包实现数据封装', advanced: '理解闭包内存泄漏风险和 IIFE 模式' },
    'P1',
  ),
  kp('JS-009', '类与原型继承', 'vibe_coding', 'javascript-basics', '面向对象', 2, 45,
    '掌握 class 语法、constructor、extends、super，理解原型链和继承机制',
    ['JS-008'], ['JS-010', 'NODE-005'], ['javascript', 'oop'],
    { basic: '能用 class 定义类并创建实例', intermediate: '能用 extends 实现继承，理解 super', advanced: '理解原型链机制，能用 Object.create 实现组合继承' },
    'P1',
  ),
  kp('JS-010', 'Promise 与异步', 'vibe_coding', 'javascript-basics', '异步编程', 3, 60,
    '理解 Promise 状态机、链式调用、错误处理，掌握 Promise.all/race/allSettled',
    ['JS-005', 'JS-009'], ['JS-011', 'NODE-003'], ['javascript', 'async'],
    { basic: '能创建 Promise 并用 .then/.catch 处理', intermediate: '能用 Promise.all 并行处理多个异步', advanced: '能实现 Promise 的错误恢复和超时机制' },
    'P1',
  ),
  kp('JS-011', 'async/await', 'vibe_coding', 'javascript-basics', '异步编程', 3, 40,
    '掌握 async 函数和 await 关键字，理解异步迭代和顶层 await，对比 Promise 链',
    ['JS-007', 'JS-010'], ['NODE-003', 'REACT-005'], ['javascript', 'async'],
    { basic: '能用 async/await 编写异步函数', intermediate: '能用 try/catch 处理异步错误', advanced: '理解异步迭代器 for await...of 和顶层 await' },
    'P1',
  ),
  kp('JS-012', 'ES Modules', 'vibe_coding', 'javascript-basics', '模块化', 2, 30,
    '掌握 import/export 语法、默认导出、命名导出、动态 import()，理解模块解析',
    ['JS-004'], ['NODE-001', 'REACT-001'], ['javascript', 'modules'],
    { basic: '能用 import/export 组织代码', intermediate: '理解默认导出和命名导出的区别', advanced: '能用动态 import() 实现代码分割' },
    'P1',
  ),
  kp('JS-013', '错误处理与调试', 'vibe_coding', 'javascript-basics', '工程实践', 2, 35,
    '掌握 try/catch/finally、自定义错误、错误传播，掌握浏览器 DevTools 调试技巧',
    ['JS-003', 'JS-004'], ['NODE-004', 'ENG-001'], ['javascript', 'debugging'],
    { basic: '能用 try/catch 捕获并处理错误', intermediate: '能创建自定义 Error 类', advanced: '理解错误冒泡和异步错误处理模式' },
    'P1',
  ),
  kp('JS-014', '生成器与迭代器', 'vibe_coding', 'javascript-basics', '高级特性', 3, 40,
    '掌握 Generator 函数、yield 表达式、可迭代协议与迭代器协议，理解生成器的惰性求值和无限序列',
    ['JS-005', 'JS-008'], ['NODE-013'], ['javascript', 'functional'],
    { basic: '能用 function* 定义生成器并用 next() 迭代', intermediate: '理解 yield 委托和可迭代协议', advanced: '能用生成器实现惰性数据管道和异步迭代' },
    'P2',
  ),
  // --- JS 进阶知识点（Step 2 新增） ---
  kp('JS-015', '正则表达式', 'vibe_coding', 'javascript-basics', '文本处理', 2, 45,
    '掌握正则语法、常用模式、RegExp 对象方法、表单验证实战',
    ['JS-004'], ['JS-016'], ['javascript', 'regex', 'validation'],
    { basic: '能用正则字面量和 RegExp 构造函数创建模式', intermediate: '能编写邮箱、手机号等常用验证正则', advanced: '能使用前瞻、后顾和命名分组处理复杂文本' },
    'P1',
  ),
  kp('JS-016', 'Map 与 Set', 'vibe_coding', 'javascript-basics', '数据结构', 2, 30,
    '掌握 Map/Set/WeakMap/WeakSet 的用法、与 Object/Array 的对比和适用场景',
    ['JS-005'], ['JS-017', 'NODE-020'], ['javascript', 'data-structure'],
    { basic: '能用 Map 存储键值对，用 Set 去重', intermediate: '理解 Map 与 Object、Set 与 Array 的区别', advanced: '能使用 WeakMap/WeakSet 管理对象引用和避免内存泄漏' },
    'P1',
  ),
  kp('JS-017', 'Proxy 与 Reflect', 'vibe_coding', 'javascript-basics', '元编程', 3, 40,
    '掌握 Proxy 拦截器、Reflect API、响应式代理模式，理解 Vue3 响应式原理',
    ['JS-008', 'JS-016'], ['JS-020'], ['javascript', 'metaprogramming'],
    { basic: '能用 Proxy 创建基本拦截器', intermediate: '能用 Reflect 配合 Proxy 实现属性拦截', advanced: '能实现响应式代理和观察者模式' },
    'P1',
  ),
  kp('JS-018', '事件循环深入', 'vibe_coding', 'javascript-basics', '运行时', 3, 35,
    '深入理解事件循环机制、宏任务与微任务、requestAnimationFrame、Node.js 事件循环差异',
    ['JS-010'], ['NODE-001'], ['javascript', 'event-loop'],
    { basic: '理解宏任务和微任务的执行顺序', intermediate: '能用 Promise 和 setTimeout 分析执行时序', advanced: '理解 Node.js 事件循环 6 阶段和浏览器差异' },
    'P1',
  ),
  kp('JS-019', '函数式编程基础', 'vibe_coding', 'javascript-basics', '编程范式', 2, 40,
    '掌握纯函数、不可变性、高阶函数、函数组合、柯里化，理解函数式编程核心思想',
    ['JS-004'], ['REACT-013'], ['javascript', 'functional'],
    { basic: '能编写纯函数和高阶函数', intermediate: '能用 compose/pipe 组合函数', advanced: '能实现柯里化和偏应用，理解 Monad 概念' },
    'P1',
  ),
  kp('JS-020', '设计模式入门', 'vibe_coding', 'javascript-basics', '工程实践', 3, 45,
    '掌握常用设计模式（单例、观察者、策略、工厂、装饰器），理解模式在 JS/TS 中的应用',
    ['JS-009'], ['REACT-013', 'NODE-005'], ['javascript', 'design-patterns'],
    { basic: '理解单例和观察者模式', intermediate: '能用策略模式和工厂模式解耦代码', advanced: '能用装饰器模式和适配器模式扩展功能' },
    'P1',
  ),
  kp('JS-021', 'TypeScript 基础', 'vibe_coding', 'javascript-basics', '类型系统', 2, 50,
    '掌握 TypeScript 基础类型、接口、类型别名、联合类型、泛型入门，从 JS 平滑过渡到 TS',
    ['JS-012'], ['ENG-002', 'REACT-009'], ['typescript', 'types'],
    { basic: '能为基础变量和函数添加类型注解', intermediate: '能用接口和类型别名定义数据结构', advanced: '能使用泛型编写可复用的类型安全函数' },
    'P1',
  ),
];

// ============================================================
// Module 2: Node.js 基础 (nodejs-basics)
// 服务端 JavaScript 开发
// ============================================================

const NODEJS_BASICS: Partial<KnowledgePoint>[] = [
  kp('NODE-001', 'Node.js 运行时与模块系统', 'vibe_coding', 'nodejs-basics', '运行时', 2, 40,
    '理解 Node.js 事件循环、CommonJS 与 ESM 模块系统、内置模块概览',
    ['JS-012'], ['NODE-002', 'NODE-003'], ['nodejs', 'runtime'],
    { basic: '能用 require/module.exports 组织代码', intermediate: '理解 CommonJS 和 ESM 的区别', advanced: '理解事件循环的 6 个阶段和微任务调度' },
    'P0',
  ),
  kp('NODE-002', '文件系统操作', 'vibe_coding', 'nodejs-basics', '内置模块', 2, 35,
    '掌握 fs 模块的同步/异步/Promise API，理解路径处理和文件流',
    ['NODE-001'], ['NODE-006'], ['nodejs', 'fs'],
    { basic: '能用 fs.readFile/readFileSync 读写文件', intermediate: '能用 fs.promises 异步 API，处理路径', advanced: '能用 Stream 处理大文件，理解背压机制' },
    'P0',
  ),
  kp('NODE-003', 'HTTP 服务器', 'vibe_coding', 'nodejs-basics', '网络编程', 3, 50,
    '掌握 http 模块创建服务器、请求/响应处理、路由基础、状态码和请求方法',
    ['JS-011', 'NODE-001'], ['NODE-004'], ['nodejs', 'http'],
    { basic: '能用 http.createServer 创建基本服务器', intermediate: '能处理 GET/POST 请求和路由', advanced: '理解 Keep-Alive、流式响应和 HTTP/2' },
    'P0',
  ),
  kp('NODE-004', 'NestJS 框架入门', 'vibe_coding', 'nodejs-basics', '框架', 3, 60,
    '理解 NestJS 架构思想（模块/控制器/服务/依赖注入），能搭建基础项目',
    ['NODE-003', 'JS-013'], ['NODE-005', 'REACT-009'], ['nodejs', 'nestjs'],
    { basic: '能创建 NestJS 项目并编写 Controller', intermediate: '能使用 Module 和 Service 分层', advanced: '理解依赖注入原理和自定义 Provider' },
    'P0',
  ),
  kp('NODE-005', 'NestJS 中间件与守卫', 'vibe_coding', 'nodejs-basics', '框架', 3, 45,
    '掌握 NestJS 中间件、守卫、拦截器、管道、过滤器的概念和使用',
    ['JS-009', 'NODE-004'], ['NODE-006', 'NODE-011'], ['nodejs', 'nestjs'],
    { basic: '能编写和使用守卫和拦截器', intermediate: '能用管道验证数据，用过滤器统一错误格式', advanced: '能自定义中间件实现 AOP 切面逻辑' },
    'P1',
  ),
  kp('NODE-006', '数据库集成', 'vibe_coding', 'nodejs-basics', '数据层', 3, 55,
    '掌握 TypeORM 集成、实体定义、Repository 模式、迁移管理',
    ['NODE-002', 'NODE-005'], ['NODE-007'], ['nodejs', 'database', 'typeorm'],
    { basic: '能定义 Entity 并执行基本 CRUD', intermediate: '能用 QueryBuilder 构建复杂查询', advanced: '理解事务、迁移和连接池配置' },
    'P1',
  ),
  kp('NODE-007', 'RESTful API 设计', 'vibe_coding', 'nodejs-basics', 'API设计', 3, 45,
    '掌握 REST 设计原则、资源路由、分页/过滤/排序、版本管理和 Swagger 文档',
    ['NODE-006'], ['NODE-008'], ['nodejs', 'api', 'rest'],
    { basic: '能设计符合 REST 规范的 CRUD 接口', intermediate: '能实现分页、过滤和排序', advanced: '理解 HATEOAS、API 版本策略和 OpenAPI 规范' },
    'P1',
  ),
  kp('NODE-008', 'WebSocket 实时通信', 'vibe_coding', 'nodejs-basics', '实时通信', 3, 40,
    '掌握 WebSocket 原理、Socket.IO 使用、房间/命名空间、实时数据推送',
    ['NODE-007'], ['NODE-014', 'REACT-005'], ['nodejs', 'websocket'],
    { basic: '能用 Socket.IO 建立实时通信', intermediate: '能使用房间和命名空间管理连接', advanced: '理解 WebSocket 协议和心跳机制' },
    'P1',
  ),
  kp('NODE-009', '认证与授权', 'vibe_coding', 'nodejs-basics', '安全', 3, 50,
    '掌握 JWT 认证流程、Passport 策略、RBAC 权限控制、OAuth 2.0 概念',
    ['NODE-004', 'JS-010'], ['NODE-011'], ['nodejs', 'auth', 'jwt'],
    { basic: '能实现 JWT 登录和接口保护', intermediate: '能实现基于角色的访问控制', advanced: '理解 OAuth 2.0 授权码流程和刷新令牌机制' },
    'P1',
  ),
  kp('NODE-010', '环境变量与配置管理', 'vibe_coding', 'nodejs-basics', '工程实践', 2, 25,
    '掌握 dotenv、ConfigModule、多环境配置、配置验证',
    ['NODE-001'], ['NODE-004', 'ENG-002'], ['nodejs', 'config'],
    { basic: '能用 .env 管理环境变量', intermediate: '能实现多环境配置和验证', advanced: '理解配置中心和安全凭证管理' },
    'P1',
  ),
  kp('NODE-011', 'JWT 认证流程', 'vibe_coding', 'nodejs-basics', '安全', 3, 45,
    '掌握 JWT 签发与验证流程、NestJS JWT + Guard 集成、异常过滤器与结构化日志',
    ['NODE-009', 'NODE-005'], ['NODE-012'], ['nodejs', 'nestjs', 'jwt'],
    { basic: '能实现 JWT 登录签发和路由保护', intermediate: '能用 JwtStrategy + AuthGuard 保护接口', advanced: '能实现 Refresh Token 和多因素认证' },
    'P1',
  ),
  kp('NODE-012', 'NestJS 异常过滤器', 'vibe_coding', 'nodejs-basics', '框架', 3, 35,
    '掌握 NestJS 异常过滤器、结构化日志（winston/pino），理解 GraphQL 核心概念',
    ['NODE-011'], ['NODE-013'], ['nodejs', 'nestjs', 'graphql'],
    { basic: '能用内置异常过滤器统一错误格式', intermediate: '能自定义异常过滤器和日志中间件', advanced: '理解 GraphQL Schema 和 Resolver 设计' },
    'P1',
  ),
  kp('NODE-013', 'GraphQL 核心概念', 'vibe_coding', 'nodejs-basics', 'API设计', 3, 50,
    '理解 GraphQL Schema/Query/Mutation/Subscription、NestJS GraphQL 模块集成',
    ['NODE-012'], ['NODE-014'], ['nodejs', 'graphql'],
    { basic: '理解 GraphQL 与 REST 的区别', intermediate: '能定义 Schema 和编写 Resolver', advanced: '能用 DataLoader 解决 N+1 问题' },
    'P2',
  ),
  kp('NODE-014', 'WebSocket 原理', 'vibe_coding', 'nodejs-basics', '实时通信', 3, 40,
    '理解 WebSocket 协议原理、NestJS WebSocket Gateway、Redis 缓存与 Docker 容器化',
    ['NODE-008', 'NODE-013'], ['NODE-015'], ['nodejs', 'websocket', 'redis'],
    { basic: '理解 WebSocket 与 HTTP 的区别', intermediate: '能用 NestJS Gateway 实现实时通信', advanced: '能设计 WebSocket 集群和房间管理' },
    'P2',
  ),
  kp('NODE-015', 'Redis 缓存', 'vibe_coding', 'nodejs-basics', '缓存', 3, 45,
    '掌握 Redis 核心数据结构、缓存策略、Docker 部署、Jest/Vitest 测试基础',
    ['NODE-014'], ['NODE-016'], ['nodejs', 'redis', 'testing'],
    { basic: '能用 Redis 存取字符串和哈希', intermediate: '能实现缓存穿透/击穿/雪崩防护', advanced: '理解 Redis 持久化和集群模式' },
    'P1',
  ),
  kp('NODE-016', 'Jest/Vitest 基础', 'vibe_coding', 'nodejs-basics', '测试', 3, 45,
    '掌握 Jest/Vitest 测试框架、NestJS 测试模块、Git 协作工作流与 CI/CD 自动化',
    ['NODE-015'], ['NODE-017'], ['nodejs', 'testing', 'git'],
    { basic: '能编写和运行单元测试', intermediate: '能用 NestJS TestingModule 测试 Controller/Service', advanced: '能配置 CI 自动化测试流水线' },
    'P1',
  ),
  kp('NODE-017', 'Git 协作工作流', 'vibe_coding', 'nodejs-basics', '工程实践', 2, 35,
    '掌握 Git 分支策略、Code Review、CI/CD 自动化、Cluster 多进程与 PM2 进程管理',
    ['NODE-016'], ['NODE-018'], ['nodejs', 'git', 'devops'],
    { basic: '能使用 Git 分支和 Pull Request 协作', intermediate: '能配置 GitHub Actions 自动化流程', advanced: '理解 Git Flow 和 Trunk-Based 开发' },
    'P1',
  ),
  kp('NODE-018', 'Cluster 多进程', 'vibe_coding', 'nodejs-basics', '性能', 4, 45,
    '掌握 Node.js Cluster 模块、PM2 进程管理、微服务基础与 NestJS 微服务',
    ['NODE-017'], ['NODE-019'], ['nodejs', 'performance', 'microservice'],
    { basic: '理解 Node.js 单线程和 Cluster 原理', intermediate: '能用 PM2 部署和管理多进程', advanced: '理解进程间通信和负载均衡' },
    'P2',
  ),
  kp('NODE-019', '微服务基础', 'vibe_coding', 'nodejs-basics', '架构', 4, 55,
    '理解微服务架构、NestJS 微服务模块、消息队列原理',
    ['NODE-018'], ['NODE-020'], ['nodejs', 'microservice'],
    { basic: '理解单体与微服务的区别', intermediate: '能用 NestJS Microservice 实现服务通信', advanced: '理解服务发现、熔断和链路追踪' },
    'P2',
  ),
  kp('NODE-020', '消息队列原理', 'vibe_coding', 'nodejs-basics', '中间件', 4, 45,
    '理解消息队列模型、健康检查与监控、APM 与链路追踪',
    ['NODE-019'], ['NODE-021'], ['nodejs', 'mq', 'monitoring'],
    { basic: '理解消息队列的作用和模型', intermediate: '能用 RabbitMQ/Redis 实现简单队列', advanced: '理解消息确认、重试和死信队列' },
    'P3',
  ),
  kp('NODE-021', '健康检查与监控', 'vibe_coding', 'nodejs-basics', '运维', 3, 40,
    '掌握健康检查端点、APM 监控、技术选型决策框架与性能优化策略',
    ['NODE-020'], ['NODE-022'], ['nodejs', 'monitoring'],
    { basic: '能实现 /health 健康检查端点', intermediate: '能集成 APM 监控和告警', advanced: '理解分布式追踪和 SLO/SLI 体系' },
    'P2',
  ),
  kp('NODE-022', '技术选型决策框架', 'vibe_coding', 'nodejs-basics', '架构', 4, 40,
    '掌握技术选型方法论、性能优化策略、LLM 基础概念',
    ['NODE-021'], ['NODE-023'], ['nodejs', 'architecture'],
    { basic: '能列举常见技术选型的考量维度', intermediate: '能根据业务场景做出合理选型', advanced: '能设计技术评估矩阵和迁移方案' },
    'P3',
  ),
  kp('NODE-023', 'LLM 基础概念', 'vibe_coding', 'nodejs-basics', 'AI', 3, 45,
    '理解 LLM 工作原理、AI Agent 与 RAG 架构基础',
    ['NODE-022'], ['AI-001', 'AI-002'], ['nodejs', 'ai', 'llm'],
    { basic: '理解大语言模型的基本原理', intermediate: '能用 API 调用 LLM 并设计 Prompt', advanced: '理解 RAG 检索增强和 Agent 工具调用' },
    'P2',
  ),
  // --- Node.js 进阶知识点（Step 3 新增） ---
  kp('NODE-024', '日志体系', 'vibe_coding', 'nodejs-basics', '工程实践', 2, 35,
    '掌握 Winston/Pino 日志框架、日志分级、结构化日志、日志轮转与集中收集',
    ['NODE-004'], ['NODE-025'], ['nodejs', 'logging'],
    { basic: '能用 Winston 记录分级日志', intermediate: '能实现结构化日志和日志轮转', advanced: '能设计日志集中收集和告警方案' },
    'P1',
  ),
  kp('NODE-025', '环境变量与配置管理深入', 'vibe_coding', 'nodejs-basics', '工程实践', 2, 30,
    '掌握 ConfigModule 高级用法、配置验证、多环境策略、配置中心概念',
    ['NODE-001'], ['NODE-028'], ['nodejs', 'config'],
    { basic: '能用 ConfigModule 管理配置', intermediate: '能实现配置验证和多环境策略', advanced: '理解配置中心和动态配置更新' },
    'P1',
  ),
  kp('NODE-026', '定时任务', 'vibe_coding', 'nodejs-basics', '工程实践', 2, 35,
    '掌握 NestJS Schedule、Cron 表达式、定时任务管理与监控',
    ['NODE-003'], ['NODE-024'], ['nodejs', 'schedule'],
    { basic: '能用 @Cron 装饰器定义定时任务', intermediate: '能编写复杂 Cron 表达式和管理任务', advanced: '能实现分布式定时任务和失败重试' },
    'P1',
  ),
  kp('NODE-027', '文件上传深入', 'vibe_coding', 'nodejs-basics', '文件处理', 2, 35,
    '掌握 Multer 配置、文件校验、分片上传、对象存储集成（S3/OSS）',
    ['NODE-002'], ['NODE-007'], ['nodejs', 'upload'],
    { basic: '能用 Multer 处理单文件上传', intermediate: '能实现文件类型校验和大小限制', advanced: '能实现分片上传和对象存储集成' },
    'P1',
  ),
  kp('NODE-028', '进程管理实践', 'vibe_coding', 'nodejs-basics', '运维', 2, 40,
    '掌握 PM2 进程管理、集群模式、Graceful Shutdown、健康检查',
    ['NODE-023'], ['NODE-029'], ['nodejs', 'process', 'pm2'],
    { basic: '能用 PM2 启动和管理 Node 进程', intermediate: '能配置集群模式和负载均衡', advanced: '能实现 Graceful Shutdown 和零停机部署' },
    'P1',
  ),
  kp('NODE-029', 'API 文档与版本管理', 'vibe_coding', 'nodejs-basics', '工程实践', 2, 35,
    '掌握 Swagger/OpenAPI 文档生成、API 版本策略、变更日志、文档自动化',
    ['NODE-012'], [], ['nodejs', 'api-docs', 'swagger'],
    { basic: '能用 Swagger 生成 API 文档', intermediate: '能实现 API 版本管理和变更日志', advanced: '能设计文档自动化和 API 兼容性检查' },
    'P1',
  ),
];

// ============================================================
// Module 3: 前端三件套 (frontend-basics)
// HTML + CSS + 布局
// ============================================================

const FRONTEND_BASICS: Partial<KnowledgePoint>[] = [
  kp('FE-001', 'HTML5 语义化', 'vibe_coding', 'frontend-basics', 'HTML', 1, 30,
    '掌握 HTML5 语义标签（header/nav/main/article/section/aside/footer），理解可访问性和 SEO 价值',
    [], ['FE-002', 'FE-003'], ['html', 'a11y'],
    { basic: '能使用语义标签组织页面结构', intermediate: '理解 ARIA 角色和可访问性', advanced: '能设计满足 WCAG 标准的语义化页面' },
    'P0',
  ),
  kp('FE-002', 'CSS 选择器与盒模型', 'vibe_coding', 'frontend-basics', 'CSS', 1, 35,
    '掌握选择器优先级、盒模型（content/padding/border/margin）、box-sizing、display 类型',
    ['FE-001'], ['FE-003'], ['css'],
    { basic: '能使用常见选择器设置样式', intermediate: '理解优先级和盒模型计算', advanced: '能调试复杂布局问题和优先级冲突' },
    'P0',
  ),
  kp('FE-003', 'Flexbox 弹性布局', 'vibe_coding', 'frontend-basics', '布局', 2, 40,
    '掌握 Flex 容器与项目属性、主轴/交叉轴对齐、换行、常见布局模式',
    ['FE-001', 'FE-002'], ['FE-004'], ['css', 'layout'],
    { basic: '能用 flex 实现水平/垂直居中', intermediate: '能用 Flex 实现导航栏和卡片布局', advanced: '理解 flex-grow/shrink/basis 计算和嵌套 Flex' },
    'P0',
  ),
  kp('FE-004', 'Grid 网格布局', 'vibe_coding', 'frontend-basics', '布局', 2, 40,
    '掌握 Grid 容器与项目属性、grid-template、gap、区域命名、响应式网格',
    ['FE-003'], ['FE-005'], ['css', 'layout'],
    { basic: '能用 grid-template-columns 定义网格', intermediate: '能用命名区域和 auto-fill/auto-fit', advanced: '理解隐式网格和 Subgrid' },
    'P1',
  ),
  kp('FE-005', '响应式设计', 'vibe_coding', 'frontend-basics', '布局', 2, 35,
    '掌握媒体查询、移动优先、相对单位、viewport、响应式图片',
    ['FE-004'], ['FE-006'], ['css', 'responsive'],
    { basic: '能用媒体查询适配不同屏幕', intermediate: '能实现移动优先的响应式布局', advanced: '理解 Container Query 和响应式策略' },
    'P0',
  ),
  kp('FE-006', 'CSS 动画与过渡', 'vibe_coding', 'frontend-basics', '视觉', 2, 30,
    '掌握 transition、animation、@keyframes、transform、性能优化',
    ['FE-005'], ['FE-007'], ['css', 'animation'],
    { basic: '能用 transition 实现简单过渡效果', intermediate: '能用 @keyframes 创建动画序列', advanced: '理解 GPU 加速和 will-change 优化' },
    'P1',
  ),
  kp('FE-007', 'Tailwind CSS', 'vibe_coding', 'frontend-basics', '工具', 2, 35,
    '掌握 Tailwind 工具类、配置定制、响应式前缀、暗色模式、组件抽取',
    ['FE-005'], ['REACT-001'], ['css', 'tailwind'],
    { basic: '能用 Tailwind 工具类快速构建页面', intermediate: '能自定义主题和抽取组件', advanced: '理解 JIT 模式和插件开发' },
    'P0',
  ),
  kp('FE-008', 'Fetch API 基础', 'vibe_coding', 'frontend-basics', '网络', 2, 35,
    '掌握 Fetch API 请求/响应、CORS 跨域处理、错误处理、请求拦截',
    ['JS-011'], ['REACT-005', 'NODE-003'], ['javascript', 'fetch', 'cors'],
    { basic: '能用 fetch 发起 GET/POST 请求', intermediate: '能处理 CORS 和请求错误', advanced: '能实现请求拦截器和重试机制' },
    'P0',
  ),
];

// ============================================================
// Module 4: React 基础 (react-basics)
// 组件化 UI 开发
// ============================================================

const REACT_BASICS: Partial<KnowledgePoint>[] = [
  kp('REACT-001', 'React 项目初始化', 'vibe_coding', 'react-basics', '工程化', 2, 30,
    '掌握 Vite + React 项目搭建、ESLint/Prettier 配置、目录结构规范',
    ['JS-012', 'FE-007'], ['REACT-002'], ['react', 'vite'],
    { basic: '能用 Vite 创建 React 项目', intermediate: '能配置 ESLint 和 Prettier', advanced: '理解 Vite 插件和自定义配置' },
    'P0',
  ),
  kp('REACT-002', 'JSX 与组件', 'vibe_coding', 'react-basics', '基础', 2, 35,
    '掌握 JSX 语法、函数组件、Props、children、条件渲染与列表渲染',
    ['REACT-001'], ['REACT-003'], ['react', 'jsx'],
    { basic: '能编写函数组件和使用 Props', intermediate: '能处理条件渲染和列表渲染', advanced: '理解 JSX 编译原理和渲染优化' },
    'P0',
  ),
  kp('REACT-003', 'State 与事件', 'vibe_coding', 'react-basics', '状态管理', 2, 40,
    '掌握 useState、事件处理、受控组件、表单处理、状态提升',
    ['REACT-002', 'JS-007', 'JS-008'], ['REACT-004'], ['react', 'state'],
    { basic: '能用 useState 管理组件状态', intermediate: '能处理表单和受控组件', advanced: '理解状态提升和单向数据流' },
    'P0',
  ),
  kp('REACT-004', 'useEffect 与副作用', 'vibe_coding', 'react-basics', '副作用', 3, 45,
    '掌握 useEffect、依赖数组、cleanup、常见副作用模式、严格模式',
    ['REACT-003'], ['REACT-005'], ['react', 'hooks'],
    { basic: '能用 useEffect 执行副作用', intermediate: '能正确设置依赖数组和 cleanup', advanced: '理解严格模式双重调用和竞态处理' },
    'P1',
  ),
  kp('REACT-005', '数据获取模式', 'vibe_coding', 'react-basics', '数据层', 3, 40,
    '掌握 fetch/axios 数据获取、加载/错误状态、自定义 Hook、SWR/React Query 基础',
    ['REACT-004', 'JS-011', 'FE-008'], ['REACT-006'], ['react', 'data-fetching'],
    { basic: '能用 fetch 获取数据并处理状态', intermediate: '能封装自定义 Hook 和处理缓存', advanced: '理解 SWR stale-while-revalidate 策略' },
    'P1',
  ),
  kp('REACT-006', '组件通信', 'vibe_coding', 'react-basics', '架构', 2, 35,
    '掌握 Props 传递、回调函数、Context API、useContext、组件组合模式',
    ['REACT-003'], ['REACT-007'], ['react', 'context'],
    { basic: '能通过 Props 和回调实现父子通信', intermediate: '能用 Context 实现跨层传递', advanced: '理解 Context 性能问题和组件组合' },
    'P1',
  ),
  kp('REACT-007', '自定义 Hook', 'vibe_coding', 'react-basics', '复用', 3, 35,
    '掌握自定义 Hook 设计、常见 Hook 封装模式、Hook 规则',
    ['REACT-004', 'REACT-006'], ['REACT-008'], ['react', 'hooks'],
    { basic: '能封装简单的自定义 Hook', intermediate: '能设计可复用的 Hook 接口', advanced: '理解 Hook 闭包陷阱和最佳实践' },
    'P1',
  ),
  kp('REACT-008', 'React Router', 'vibe_coding', 'react-basics', '路由', 3, 40,
    '掌握 React Router v6、路由配置、嵌套路由、动态路由、导航守卫',
    ['REACT-001', 'REACT-003'], ['REACT-009'], ['react', 'router'],
    { basic: '能配置基本路由和页面切换', intermediate: '能实现嵌套路由和动态参数', advanced: '能实现路由守卫和代码分割' },
    'P1',
  ),
  kp('REACT-009', 'TypeScript 与 React', 'vibe_coding', 'react-basics', '类型', 3, 40,
    '掌握 React TypeScript 组件类型、Props/State 泛型、事件类型、工具类型',
    ['REACT-002', 'NODE-004'], ['REACT-010'], ['react', 'typescript'],
    { basic: '能为函数组件和 Props 添加类型', intermediate: '能使用泛型和工具类型', advanced: '能设计类型安全的 Hook 和 Context' },
    'P1',
  ),
  kp('REACT-010', '表单与校验', 'vibe_coding', 'react-basics', '表单', 3, 40,
    '掌握 React Hook Form、Zod 校验、表单 UX 优化、动态表单',
    ['REACT-003', 'REACT-009'], ['REACT-011'], ['react', 'form'],
    { basic: '能用 React Hook Form 管理表单', intermediate: '能用 Zod 定义校验规则', advanced: '能实现动态表单和条件字段' },
    'P1',
  ),
  kp('REACT-011', '性能优化', 'vibe_coding', 'react-basics', '性能', 3, 40,
    '掌握 React.memo、useMemo、useCallback、虚拟化列表、性能分析',
    ['REACT-004', 'REACT-007'], ['REACT-012'], ['react', 'performance'],
    { basic: '能用 memo 避免不必要渲染', intermediate: '能用 useMemo/useCallback 优化计算', advanced: '能用 Profiler 分析和优化渲染瓶颈' },
    'P1',
  ),
  kp('REACT-012', 'React DevTools', 'vibe_coding', 'react-basics', '工具', 2, 25,
    '掌握 React DevTools 组件树检查、Props/State 调试、Profiler 性能分析',
    ['REACT-003'], ['REACT-013'], ['react', 'devtools'],
    { basic: '能用 DevTools 检查组件树', intermediate: '能追踪 Props 和 State 变化', advanced: '能用 Profiler 定位性能瓶颈' },
    'P1',
  ),
  kp('REACT-013', '组件设计模式', 'vibe_coding', 'react-basics', '架构', 3, 40,
    '掌握 Compound Component、Render Props、HOC、Headless Component 设计模式',
    ['REACT-006', 'REACT-007'], ['REACT-014'], ['react', 'patterns'],
    { basic: '理解组件设计的基本原则', intermediate: '能实现 Compound Component 模式', advanced: '能设计 Headless Component 和自定义 API' },
    'P2',
  ),
  kp('REACT-014', '状态管理方案', 'vibe_coding', 'react-basics', '状态管理', 3, 45,
    '掌握 Zustand/Jotai 等轻量状态管理、Store 设计、中间件、DevTools 集成',
    ['REACT-006', 'REACT-011'], ['REACT-015'], ['react', 'state-management'],
    { basic: '能用 Zustand 创建和读取 Store', intermediate: '能设计合理的 Store 结构和中间件', advanced: '理解状态管理选型和性能优化' },
    'P1',
  ),
  kp('REACT-015', 'Next.js App Router', 'vibe_coding', 'react-basics', '框架', 3, 50,
    '掌握 Next.js App Router、Server Components、Server Actions、数据获取策略',
    ['REACT-008', 'REACT-014'], ['REACT-016'], ['react', 'nextjs'],
    { basic: '能创建 Next.js 项目和页面路由', intermediate: '能用 Server Components 和 Server Actions', advanced: '理解 SSR/SSG/ISR 策略和缓存机制' },
    'P1',
  ),
  kp('REACT-016', '项目目录规范', 'vibe_coding', 'react-basics', '工程化', 2, 30,
    '掌握项目目录组织、组件设计原则、Suspense 与懒加载',
    ['REACT-015'], ['REACT-017'], ['react', 'architecture'],
    { basic: '能按功能模块组织项目目录', intermediate: '能设计可复用的组件结构', advanced: '理解领域驱动目录设计和模块边界' },
    'P1',
  ),
  kp('REACT-017', 'Suspense 与懒加载', 'vibe_coding', 'react-basics', '性能', 3, 35,
    '掌握 React.lazy、Suspense、Transitions、useTransition',
    ['REACT-016'], ['REACT-018'], ['react', 'performance'],
    { basic: '能用 React.lazy 和 Suspense 实现代码分割', intermediate: '能用 useTransition 实现非阻塞更新', advanced: '理解 Suspense 数据获取架构' },
    'P2',
  ),
  kp('REACT-018', 'React Testing Library', 'vibe_coding', 'react-basics', '测试', 3, 40,
    '掌握 React Testing Library、测试模式（渲染/交互/异步）、测试最佳实践',
    ['REACT-017'], ['ENG-003'], ['react', 'testing'],
    { basic: '能编写组件渲染和交互测试', intermediate: '能测试异步操作和用户交互', advanced: '能设计可测试的组件架构和 Mock 策略' },
    'P1',
  ),
  // --- React 生态进阶知识点（Step 4 新增） ---
  kp('REACT-019', 'React Server Components', 'vibe_coding', 'react-basics', '服务端渲染', 3, 40,
    '理解 RSC 架构、服务端组件与客户端组件区别、数据获取模式、流式渲染',
    ['REACT-011', 'REACT-017'], ['REACT-020'], ['react', 'rsc', 'server-components'],
    { basic: '理解服务端组件和客户端组件的区别', intermediate: '能用 RSC 实现直接数据获取', advanced: '理解流式渲染和 RSC 序列化协议' },
    'P1',
  ),
  kp('REACT-020', 'Next.js App Router', 'vibe_coding', 'react-basics', '框架', 3, 45,
    '掌握 Next.js App Router、布局嵌套、Server Actions、中间件、路由分组',
    ['REACT-019'], ['REACT-022'], ['react', 'nextjs', 'app-router'],
    { basic: '能用 App Router 创建页面和布局', intermediate: '能使用 Server Actions 和中间件', advanced: '理解路由分组、并行路由和拦截路由' },
    'P1',
  ),
  kp('REACT-021', '数据获取策略', 'vibe_coding', 'react-basics', '数据层', 2, 40,
    '掌握 SWR/React Query 数据获取策略、缓存与重新验证、乐观更新、无限滚动',
    ['REACT-005', 'REACT-016'], [], ['react', 'data-fetching', 'swr'],
    { basic: '能用 SWR 或 React Query 获取数据', intermediate: '能配置缓存策略和重新验证', advanced: '能实现乐观更新和无限滚动加载' },
    'P1',
  ),
  kp('REACT-022', '国际化与无障碍', 'vibe_coding', 'react-basics', '工程实践', 2, 35,
    '掌握 next-intl 国际化方案、ARIA 无障碍属性、语义化 HTML、键盘导航',
    ['REACT-002'], [], ['react', 'i18n', 'accessibility'],
    { basic: '能用 next-intl 实现基本国际化', intermediate: '能添加 ARIA 属性提升无障碍', advanced: '能实现完整的键盘导航和屏幕阅读器支持' },
    'P1',
  ),
  kp('REACT-023', '组件设计模式', 'vibe_coding', 'react-basics', '架构', 3, 45,
    '掌握复合组件、Render Props、HOC、Headless Component、受控与非受控模式',
    ['REACT-007', 'JS-019'], [], ['react', 'patterns', 'design'],
    { basic: '理解受控与非受控组件区别', intermediate: '能用复合组件和 Render Props 封装逻辑', advanced: '能设计 Headless Component 实现逻辑与 UI 分离' },
    'P1',
  ),
];

// ============================================================
// Module 5: 工程化与部署 (engineering)
// 代码规范、类型系统、API 设计
// ============================================================

const ENGINEERING: Partial<KnowledgePoint>[] = [
  kp('ENG-001', 'ESLint 代码检查', 'vibe_coding', 'engineering', '规范', 2, 30,
    '掌握 ESLint 配置、Prettier 格式化、TypeScript 进阶类型、类型守卫与 discriminated union',
    ['JS-013'], ['ENG-002'], ['eslint', 'prettier'],
    { basic: '能配置 ESLint 和 Prettier', intermediate: '能自定义规则和修复脚本', advanced: '能编写自定义 ESLint 插件' },
    'P1',
  ),
  kp('ENG-002', 'TypeScript 进阶类型', 'vibe_coding', 'engineering', '类型系统', 3, 45,
    '掌握 TypeScript 高级类型（泛型/条件类型/映射类型）、类型守卫、discriminated union',
    ['ENG-001', 'NODE-010'], ['ENG-003'], ['typescript', 'types'],
    { basic: '能使用泛型和工具类型', intermediate: '能用条件类型和映射类型', advanced: '能设计类型安全的 API 和类型体操' },
    'P1',
  ),
  kp('ENG-003', 'RESTful API 设计原则', 'vibe_coding', 'engineering', 'API设计', 3, 40,
    '掌握 RESTful 设计原则、DTO 与数据验证、AI 辅助编程工具',
    ['ENG-002', 'REACT-018'], [], ['api', 'rest', 'dto'],
    { basic: '能设计符合 REST 规范的 API', intermediate: '能用 DTO 和校验保证数据质量', advanced: '理解 API 版本化和向后兼容策略' },
    'P1',
  ),
  // --- 前端工程进阶知识点（Step 5 新增） ---
  kp('ENG-004', 'pnpm 与 Monorepo', 'vibe_coding', 'engineering', '工程实践', 2, 40,
    '掌握 pnpm 工作区、Monorepo 架构、Turborepo/Nx 构建、包依赖管理',
    ['ENG-001'], ['ENG-005'], ['pnpm', 'monorepo', 'turborepo'],
    { basic: '能用 pnpm 管理项目依赖', intermediate: '能配置 pnpm workspace 实现 Monorepo', advanced: '能用 Turborepo 优化多包构建和缓存' },
    'P1',
  ),
  kp('ENG-005', 'CI/CD 流水线', 'vibe_coding', 'engineering', 'DevOps', 2, 45,
    '掌握 GitHub Actions/GitLab CI 流水线、自动化测试、自动部署、环境管理',
    ['ENG-004'], ['ENG-007'], ['ci-cd', 'github-actions', 'devops'],
    { basic: '能编写基本 CI 流水线配置', intermediate: '能配置自动化测试和部署流程', advanced: '能设计多环境部署和回滚策略' },
    'P1',
  ),
  kp('ENG-006', '前端性能优化', 'vibe_coding', 'engineering', '性能', 3, 40,
    '掌握 Core Web Vitals、Lighthouse 审计、代码分割、图片优化、缓存策略',
    ['REACT-018'], [], ['performance', 'lighthouse', 'optimization'],
    { basic: '能用 Lighthouse 审计页面性能', intermediate: '能实现代码分割和图片懒加载', advanced: '能优化 Core Web Vitals 和设计缓存策略' },
    'P1',
  ),
  kp('ENG-007', 'Docker 容器化', 'vibe_coding', 'engineering', 'DevOps', 2, 40,
    '掌握 Dockerfile 编写、镜像构建、Docker Compose、容器编排基础',
    ['ENG-002'], [], ['docker', 'container', 'devops'],
    { basic: '能编写 Dockerfile 构建镜像', intermediate: '能用 Docker Compose 编排多服务', advanced: '能优化镜像大小和配置多阶段构建' },
    'P1',
  ),
];

// ============================================================
// Module 6: Vibe Coding 核心 (vibe-coding)
// 氛围编程范式与 AI 协作工作流
// ============================================================

const VIBE_BASICS: Partial<KnowledgePoint>[] = [
  kp('VIBE-001', 'Vibe Coding 范式理解', 'vibe_coding', 'vibe-coding', '概论', 1, 30,
    '理解 Vibe Coding 核心理念：以意图驱动、AI 协作为核心的开发范式转变',
    [], ['VIBE-002', 'VIBE-003', 'VIBE-004', 'VIBE-012'], ['vibe-coding', 'paradigm'],
    { basic: '理解 Vibe Coding 的定义和核心原则', intermediate: '能区分传统编程与 Vibe Coding 的工作流差异', advanced: '能评估项目场景是否适合 Vibe Coding 范式' },
    'P0',
  ),
  kp('VIBE-002', '角色转变：从打字员到指挥官', 'vibe_coding', 'vibe-coding', '思维转变', 1, 25,
    '理解开发者角色转变：从逐行编写代码到指挥 AI 生成、审核、迭代代码',
    ['VIBE-001'], ['VIBE-003'], ['vibe-coding', 'mindset'],
    { basic: '理解开发者从编码者到指挥者的角色变化', intermediate: '能识别哪些任务适合委托 AI、哪些需要人工把控', advanced: '能设计高效的人机协作分工策略' },
    'P0',
  ),
  kp('VIBE-003', 'Prompt Engineering 基础', 'vibe_coding', 'vibe-coding', 'Prompt', 2, 45,
    '掌握 Prompt 编写原则、结构化提示、上下文管理、温度参数与模型选择',
    ['VIBE-001'], ['VIBE-007', 'VIBE-009', 'VIBE-010', 'VIBE-011'], ['vibe-coding', 'prompt', 'engineering'],
    { basic: '能编写清晰、结构化的 Prompt', intermediate: '能用角色设定和约束条件提升输出质量', advanced: '能设计多轮对话策略和上下文管理方案' },
    'P0',
  ),
  kp('VIBE-004', '氛围抽象能力', 'vibe_coding', 'vibe-coding', '核心能力', 2, 35,
    '掌握将模糊需求抽象为可执行 Prompt 的能力，理解氛围描述的层次结构',
    ['VIBE-001'], ['VIBE-005', 'VIBE-006'], ['vibe-coding', 'abstraction'],
    { basic: '能将简单需求转化为结构化描述', intermediate: '能对模糊需求进行拆解和抽象', advanced: '能设计多层氛围描述框架覆盖复杂项目' },
    'P1',
  ),
  kp('VIBE-005', '视觉氛围描述', 'vibe_coding', 'vibe-coding', '核心能力', 2, 40,
    '掌握用 Prompt 描述 UI 视觉效果、布局结构、设计风格，实现设计到代码的转化',
    ['VIBE-004'], ['VIBE-008'], ['vibe-coding', 'visual', 'ui'],
    { basic: '能用文字描述页面布局和基本样式', intermediate: '能用设计术语描述视觉效果和交互状态', advanced: '能用 Prompt 精确还原设计稿的视觉细节' },
    'P1',
  ),
  kp('VIBE-006', '交互氛围描述', 'vibe_coding', 'vibe-coding', '核心能力', 2, 35,
    '掌握用 Prompt 描述用户交互流程、状态变化、动画效果和数据流',
    ['VIBE-004'], ['VIBE-008'], ['vibe-coding', 'interaction', 'ux'],
    { basic: '能用文字描述基本点击和表单交互', intermediate: '能描述复杂状态转换和异步交互流程', advanced: '能用 Prompt 精确描述动画时序和手势交互' },
    'P1',
  ),
  kp('VIBE-007', 'AI 代码评审', 'vibe_coding', 'vibe-coding', '质量管控', 3, 45,
    '掌握用 AI 进行代码评审的模式、评审维度、反馈迭代，建立代码质量闭环',
    ['VIBE-003'], ['VIBE-015'], ['vibe-coding', 'review', 'quality'],
    { basic: '能用 AI 审查代码的基本问题', intermediate: '能设定评审维度和标准，引导 AI 深度评审', advanced: '能建立 AI 评审自动化流程和反馈闭环' },
    'P1',
  ),
  kp('VIBE-008', 'Prompt 迭代优化', 'vibe_coding', 'vibe-coding', '核心能力', 3, 40,
    '掌握 Prompt 迭代方法：分析输出偏差、调整上下文、增加约束、逐步精化',
    ['VIBE-005', 'VIBE-006'], ['VIBE-014'], ['vibe-coding', 'iteration', 'optimization'],
    { basic: '能识别 AI 输出与期望的偏差', intermediate: '能通过调整 Prompt 逐步改善输出质量', advanced: '能设计系统化 Prompt 迭代策略和评估指标' },
    'P1',
  ),
  kp('VIBE-009', 'AI 辅助调试', 'vibe_coding', 'vibe-coding', '调试', 2, 35,
    '掌握用 AI 辅助定位和修复 Bug 的方法、错误信息解读、调试策略',
    ['VIBE-003'], [], ['vibe-coding', 'debugging'],
    { basic: '能用 AI 解读错误信息并建议修复', intermediate: '能用 AI 分析复杂 Bug 的根因', advanced: '能设计 AI 辅助调试的系统性流程' },
    'P1',
  ),
  kp('VIBE-010', '任务拆解与大需求分步', 'vibe_coding', 'vibe-coding', '项目管理', 3, 40,
    '掌握将大需求拆解为 AI 可执行的小任务、分步实施策略、依赖管理',
    ['VIBE-003'], ['VIBE-014'], ['vibe-coding', 'task-split', 'management'],
    { basic: '能将需求拆解为 AI 可执行的步骤', intermediate: '能管理步骤间的依赖关系和执行顺序', advanced: '能设计复杂项目的分步实施策略和并行方案' },
    'P1',
  ),
  kp('VIBE-011', 'Few-shot 与约束强化', 'vibe_coding', 'vibe-coding', 'Prompt', 3, 35,
    '掌握 Few-shot 示例、输出约束、格式模板、反向提示等高级 Prompt 技术',
    ['VIBE-003'], [], ['vibe-coding', 'few-shot', 'constraints'],
    { basic: '能在 Prompt 中提供示例引导输出', intermediate: '能用 JSON Schema 和格式约束控制输出', advanced: '能设计 Few-shot 策略和反向提示处理边界情况' },
    'P1',
  ),
  kp('VIBE-012', 'AI IDE 高效使用', 'vibe_coding', 'vibe-coding', '工具', 2, 35,
    '掌握 Cursor/Continue 等 AI IDE 的高效使用技巧、快捷操作、工作流集成',
    ['VIBE-001'], ['VIBE-013'], ['vibe-coding', 'ai-ide', 'cursor'],
    { basic: '能用 AI IDE 的代码补全和内联编辑', intermediate: '能使用 Chat 模式和 @引用 上下文', advanced: '能配置 AI IDE 的自定义规则和 MCP 集成' },
    'P0',
  ),
  kp('VIBE-013', '人机协作最佳实践', 'vibe_coding', 'vibe-coding', '实践', 3, 40,
    '掌握人机协作的最佳实践模式、代码归属策略、知识传承、团队协作流程',
    ['VIBE-012'], [], ['vibe-coding', 'collaboration', 'best-practices'],
    { basic: '理解人机协作的基本原则和边界', intermediate: '能设计团队 Vibe Coding 工作流和规范', advanced: '能建立代码归属策略和知识传承机制' },
    'P2',
  ),
  kp('VIBE-014', 'Vibe Coding 实战项目', 'vibe_coding', 'vibe-coding', '实战', 3, 60,
    '综合运用 Vibe Coding 全流程完成一个完整项目：需求分析→Prompt 设计→AI 生成→迭代优化→交付',
    ['VIBE-008', 'VIBE-010'], [], ['vibe-coding', 'project', 'practice'],
    { basic: '能用 Vibe Coding 完成小型项目', intermediate: '能在中等项目中运用分步迭代策略', advanced: '能在大型项目中建立 Vibe Coding 工程化流程' },
    'P2',
  ),
  kp('VIBE-015', 'AI 代码质量管控', 'vibe_coding', 'vibe-coding', '质量管控', 4, 45,
    '掌握 AI 生成代码的质量标准、自动化检测、安全审计、技术债务管理',
    ['VIBE-007'], [], ['vibe-coding', 'quality', 'governance'],
    { basic: '理解 AI 生成代码的常见质量问题', intermediate: '能建立代码质量检测和审查流程', advanced: '能设计 AI 代码安全审计和技术债务治理策略' },
    'P2',
  ),
];

// ============================================================
// Module 7: 数据库基础 (database-basics)
// SQL、NoSQL、数据库设计
// ============================================================

const DB_BASICS: Partial<KnowledgePoint>[] = [
  kp('DB-001', 'SQL 查询基础', 'vibe_coding', 'database-basics', '关系型数据库', 2, 45,
    '掌握 SQL 基础语法、CRUD 操作、JOIN 查询、子查询、聚合函数、索引概念',
    ['NODE-006'], ['DB-002', 'DB-003'], ['sql', 'database', 'relational'],
    { basic: '能编写 SELECT/INSERT/UPDATE/DELETE 语句', intermediate: '能用 JOIN 和子查询处理多表关联', advanced: '能优化复杂查询和理解索引策略' },
    'P0',
  ),
  kp('DB-002', '数据库设计原则', 'vibe_coding', 'database-basics', '设计', 2, 40,
    '掌握范式化与反范式化、ER 模型、主键/外键设计、数据完整性约束',
    ['DB-001'], ['DB-004'], ['database', 'design', 'normalization'],
    { basic: '能设计简单的表结构和主外键', intermediate: '理解三大范式和反范式化取舍', advanced: '能设计复杂 ER 模型和数据完整性策略' },
    'P1',
  ),
  kp('DB-003', 'MongoDB 基础', 'vibe_coding', 'database-basics', 'NoSQL', 2, 40,
    '掌握 MongoDB 文档模型、CRUD、聚合管道、Mongoose ODM、索引策略',
    ['DB-001'], [], ['mongodb', 'nosql', 'mongoose'],
    { basic: '能用 MongoDB 进行文档 CRUD', intermediate: '能用聚合管道处理复杂数据', advanced: '能设计 MongoDB 索引策略和分片方案' },
    'P1',
  ),
  kp('DB-004', '数据库性能优化', 'vibe_coding', 'database-basics', '性能', 3, 45,
    '掌握慢查询分析、索引优化、连接池管理、读写分离、缓存策略',
    ['DB-002'], [], ['database', 'performance', 'optimization'],
    { basic: '能用 EXPLAIN 分析慢查询', intermediate: '能设计索引优化和连接池配置', advanced: '能设计读写分离和分库分表策略' },
    'P2',
  ),
];

// ============================================================
// Module 8: 实战项目 (projects)
// 综合实战，串联全栈技能
// ============================================================

const PROJECTS: Partial<KnowledgePoint>[] = [
  kp('PROJ-001', '个人作品集', 'vibe_coding', 'projects', '入门项目', 2, 120,
    '用 Vibe Coding 方式快速构建个人作品集网站，串联 React + 部署全流程',
    ['VIBE-005', 'REACT-002'], ['PROJ-002'], ['react', 'nextjs', 'portfolio'],
    { basic: '能用 Next.js 搭建静态作品集', intermediate: '能实现响应式布局和暗色主题', advanced: '能添加动画效果和 SEO 优化' },
    'P1',
  ),
  kp('PROJ-002', '全栈待办应用', 'vibe_coding', 'projects', '全栈项目', 3, 180,
    '构建完整全栈待办应用：React 前端 + NestJS 后端 + 数据库，掌握 CRUD 全流程',
    ['REACT-010', 'NODE-006', 'DB-001'], ['PROJ-004'], ['react', 'nestjs', 'fullstack', 'crud'],
    { basic: '能实现基本 CRUD 待办功能', intermediate: '能添加用户认证和分类筛选', advanced: '能实现实时同步和离线支持' },
    'P1',
  ),
  kp('PROJ-003', 'AI 聊天机器人', 'vibe_coding', 'projects', 'AI 项目', 3, 180,
    '构建 AI 聊天应用：流式响应、对话管理、Prompt 优化、上下文窗口管理',
    ['REACT-005', 'NODE-023', 'VIBE-003'], ['PROJ-005'], ['react', 'ai', 'chat', 'streaming'],
    { basic: '能实现基本 AI 对话功能', intermediate: '能实现流式响应和对话历史管理', advanced: '能优化 Prompt 和管理长上下文窗口' },
    'P1',
  ),
  kp('PROJ-004', '博客系统', 'vibe_coding', 'projects', '全栈项目', 4, 240,
    '构建完整博客系统：MDX 内容、评论系统、搜索、标签、RSS、SEO 全套',
    ['PROJ-002', 'REACT-020', 'DB-002'], [], ['react', 'nextjs', 'blog', 'mdx'],
    { basic: '能实现文章展示和基本 CRUD', intermediate: '能添加评论、搜索和标签系统', advanced: '能实现 MDX 渲染、RSS 和完整 SEO' },
    'P2',
  ),
  kp('PROJ-005', 'RAG 知识库', 'vibe_coding', 'projects', 'AI 项目', 4, 240,
    '构建 RAG 知识库系统：文档上传、向量化、检索、生成、管理后台',
    ['AI-001', 'DB-003', 'PROJ-003'], [], ['ai', 'rag', 'vector', 'knowledge-base'],
    { basic: '能实现文档上传和基本检索', intermediate: '能实现向量化检索和问答生成', advanced: '能优化检索策略和实现混合搜索' },
    'P2',
  ),
];

// ============================================================
// Module 9: AI + 现代开发 (ai-modern)
// Vibe Coding、AI 辅助开发
// ============================================================

const AI_MODERN: Partial<KnowledgePoint>[] = [
  kp('AI-001', 'AI 辅助编程工具', 'vibe_coding', 'ai-modern', '工具', 2, 35,
    '掌握 AI 辅助编程工具、Prompt Engineering、RAG 架构与文档切分策略',
    ['NODE-023'], ['AI-002'], ['ai', 'prompt'],
    { basic: '能用 AI IDE 生成和补全代码', intermediate: '能编写高质量 Prompt 提升输出', advanced: '理解 RAG 检索增强和文档切分策略' },
    'P1',
  ),
  kp('AI-002', 'RAG 架构', 'vibe_coding', 'ai-modern', '架构', 3, 45,
    '理解 RAG（检索增强生成）架构、文档切分、向量化、检索策略',
    ['AI-001'], ['AI-003'], ['ai', 'rag'],
    { basic: '理解 RAG 的基本流程和组件', intermediate: '能实现文档切分和向量化检索', advanced: '能设计混合检索和重排序策略' },
    'P2',
  ),
  kp('AI-003', 'AI Agent 架构', 'vibe_coding', 'ai-modern', 'Agent', 4, 50,
    '理解 AI Agent 架构、工具调用（Function Calling）、多步推理、自主决策',
    ['AI-002'], [], ['ai', 'agent'],
    { basic: '理解 Agent 的基本概念和架构', intermediate: '能实现工具调用和多步推理', advanced: '能设计多 Agent 协作和自主决策流程' },
    'P2',
  ),
];

// ============================================================
// 汇总导出
// ============================================================

/** 全量知识点（115 个，与 lecture/exercise 完全对齐） */
export const ALL_KNOWLEDGE_POINTS: Partial<KnowledgePoint>[] = [
  ...JS_BASICS,
  ...NODEJS_BASICS,
  ...FRONTEND_BASICS,
  ...REACT_BASICS,
  ...DB_BASICS,
  ...ENGINEERING,
  ...AI_MODERN,
  ...VIBE_BASICS,
  ...PROJECTS,
];

/** 按模块分组 */
export const KNOWLEDGE_BY_MODULE: Record<string, Partial<KnowledgePoint>[]> = {
  'javascript-basics': JS_BASICS,
  'nodejs-basics': NODEJS_BASICS,
  'frontend-basics': FRONTEND_BASICS,
  'react-basics': REACT_BASICS,
  'database-basics': DB_BASICS,
  engineering: ENGINEERING,
  'ai-modern': AI_MODERN,
  'vibe-coding': VIBE_BASICS,
  projects: PROJECTS,
};

/** 模块排序（学习路径顺序） */
export const MODULE_ORDER = [
  'javascript-basics',
  'nodejs-basics',
  'frontend-basics',
  'react-basics',
  'database-basics',
  'engineering',
  'ai-modern',
  'vibe-coding',
  'projects',
];

/** 模块显示名映射 */
export const MODULE_DISPLAY_NAMES: Record<string, string> = {
  'javascript-basics': 'JavaScript 核心基础',
  'nodejs-basics': 'Node.js 服务端开发',
  'frontend-basics': '前端三件套',
  'react-basics': 'React 基础',
  'database-basics': '数据库基础',
  engineering: '工程化与部署',
  'ai-modern': 'AI + 现代开发',
  'vibe-coding': 'Vibe Coding 核心',
  projects: '实战项目',
};

/** 统计信息 */
export const KNOWLEDGE_STATS = {
  totalPoints: ALL_KNOWLEDGE_POINTS.length,
  modules: MODULE_ORDER.length,
  byDifficulty: {
    1: ALL_KNOWLEDGE_POINTS.filter(k => k.difficulty === 1).length,
    2: ALL_KNOWLEDGE_POINTS.filter(k => k.difficulty === 2).length,
    3: ALL_KNOWLEDGE_POINTS.filter(k => k.difficulty === 3).length,
    4: ALL_KNOWLEDGE_POINTS.filter(k => k.difficulty === 4).length,
    5: ALL_KNOWLEDGE_POINTS.filter(k => k.difficulty === 5).length,
  },
  byModule: Object.fromEntries(
    Object.entries(KNOWLEDGE_BY_MODULE).map(([mod, kps]) => [mod, kps.length])
  ),
  totalEstimatedHours: Math.round(
    ALL_KNOWLEDGE_POINTS.reduce((sum, kp) => sum + (kp.estimatedMinutes || 0), 0) / 60
  ),
};
