"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ErrorMessages = exports.ErrorCodes = void 0;
exports.ErrorCodes = {
    SUCCESS: 0,
    TOKEN_EXPIRED: 1001,
    TOKEN_INVALID: 1002,
    PERMISSION_DENIED: 1003,
    UNAUTHORIZED: 1004,
    USER_NOT_FOUND: 2001,
    USER_EMAIL_EXISTS: 2002,
    PASSWORD_WRONG: 2003,
    USER_DISABLED: 2004,
    COURSE_NOT_FOUND: 3001,
    EXERCISE_NOT_FOUND: 3002,
    KNOWLEDGE_POINT_NOT_FOUND: 3003,
    LEARNING_PATH_NOT_FOUND: 3004,
    SUBMISSION_NOT_FOUND: 3005,
    EXECUTION_TIMEOUT: 4001,
    MEMORY_LIMIT_EXCEEDED: 4002,
    SANDBOX_ERROR: 4003,
    AGENT_UNAVAILABLE: 5001,
    LLM_TIMEOUT: 5002,
    LLM_RATE_LIMIT: 5003,
    AGENT_INVALID_RESPONSE: 5004,
    INTERNAL_ERROR: 9001,
    SERVICE_UNAVAILABLE: 9002,
    BAD_REQUEST: 9003,
    VALIDATION_ERROR: 9004,
};
exports.ErrorMessages = {
    [exports.ErrorCodes.SUCCESS]: 'success',
    [exports.ErrorCodes.TOKEN_EXPIRED]: 'Token 已过期',
    [exports.ErrorCodes.TOKEN_INVALID]: 'Token 无效',
    [exports.ErrorCodes.PERMISSION_DENIED]: '权限不足',
    [exports.ErrorCodes.UNAUTHORIZED]: '未授权访问',
    [exports.ErrorCodes.USER_NOT_FOUND]: '用户不存在',
    [exports.ErrorCodes.USER_EMAIL_EXISTS]: '邮箱已注册',
    [exports.ErrorCodes.PASSWORD_WRONG]: '密码错误',
    [exports.ErrorCodes.USER_DISABLED]: '用户已被禁用',
    [exports.ErrorCodes.COURSE_NOT_FOUND]: '课程不存在',
    [exports.ErrorCodes.EXERCISE_NOT_FOUND]: '练习不存在',
    [exports.ErrorCodes.KNOWLEDGE_POINT_NOT_FOUND]: '知识点不存在',
    [exports.ErrorCodes.LEARNING_PATH_NOT_FOUND]: '学习路径不存在',
    [exports.ErrorCodes.SUBMISSION_NOT_FOUND]: '提交记录不存在',
    [exports.ErrorCodes.EXECUTION_TIMEOUT]: '执行超时',
    [exports.ErrorCodes.MEMORY_LIMIT_EXCEEDED]: '内存超限',
    [exports.ErrorCodes.SANDBOX_ERROR]: '沙箱执行错误',
    [exports.ErrorCodes.AGENT_UNAVAILABLE]: 'Agent 不可用',
    [exports.ErrorCodes.LLM_TIMEOUT]: 'LLM 响应超时',
    [exports.ErrorCodes.LLM_RATE_LIMIT]: 'LLM 请求频率超限',
    [exports.ErrorCodes.AGENT_INVALID_RESPONSE]: 'Agent 返回异常',
    [exports.ErrorCodes.INTERNAL_ERROR]: '内部错误',
    [exports.ErrorCodes.SERVICE_UNAVAILABLE]: '服务不可用',
    [exports.ErrorCodes.BAD_REQUEST]: '请求参数错误',
    [exports.ErrorCodes.VALIDATION_ERROR]: '数据校验失败',
};
//# sourceMappingURL=error-codes.js.map